apiVersion: v1
kind: Service
metadata:
  name: orca-redis
  namespace: orca
  labels:
    app: orca-redis
spec:
  selector:
    app: orca-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orca-redis
  namespace: orca
spec:
  serviceName: orca-redis
  replicas: 1
  selector:
    matchLabels:
      app: orca-redis
  template:
    metadata:
      labels:
        app: orca-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory-policy
            - allkeys-lru
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
